### ISSUE TITLE
Duplicator Pro Archive: Error: Unable to locate database in the site archive.

### ISSUE THREAD

**Issue by GreggFranklin** [ServerPress/clean-import#33] opened 2018-09-03 18:29 UTC
#### STEPS TO REPRODUCE: 
1. Start DesktopServer
2. Turn on all plugins including Clean Import
3. Import Duplicator Pro Archive

Archive:
https://www.dropbox.com/s/as75ds5xwzux7fn/Daily_jukeboxhosting_archive.zip?dl=0

#### RESULTS: 
![image 20](https://user-images.githubusercontent.com/1041421/44998691-5445f600-af6c-11e8-8f5e-e96800ac808f.jpg)

#### EXPECTED RESULT:
Clean Import to move the database to the root and rename to database.sql

Plugin version: 1.1.5
DS Version: 3.9.2RC1
Operating System: Windows 10

**Comment by GreggFranklin** [comment] 2018-09-03 19:28
Hold off on this I think the client provided a bad package. My test was successful and his is missing a wp-config file all together.

**Comment by davejesch** [comment] 2018-09-03 19:28
Looks like the contents of the Duplicator archive are different. We're currently looking for a dup-wp-config-arc__{guid}.txt file, which does not exist in this archive. This archive has a wp-config.php file. We use the guid from the .txt file to locate the database file in the dup-installer/ directory.

So, a couple questions:
- If there's a wp-config.php and/or a missing dup-wp-config-arc__{guid}.txt file should we continue? Right now, we stop since the config file is present.
- If no dup-wp-config-arc__{guid}.txt file, is it reliable to copy the dup-installer/*.sql file into /database.sql?
- Is this a different version of Duplicator and they've changed (again) their file naming conventions? We might have to make the code a lot more resilient in order to deal with several different versions in the wild.

**Comment by davejesch** [comment] 2018-09-03 19:29
A "bad package" would explain what I'm seeing and my previous questions. Find out what you can, the answer the questions and reassign to me when you can.

**Comment by GreggFranklin** [comment] 2018-09-04 02:50
The client reported that his wp-config.php was above the root and Duplicator could not find it. Closing this ticket.

**Comment by davejesch** [comment] 2018-09-06 07:18
Need to add checks for missing wp-config.php and copy wp-config-sample.php to wp-config.php. Doing this will require searching the database for the db prefix to add to wp-config.

Also make the search for .sql file more error resistant since we're using the name of the dup-wp-config-arc__{guid}.txt to find the .sql file.

**Comment by davejesch** [comment] 2018-09-06 18:04
There is no dup-wp-config-arc__{guid}.txt file in the archive- this is the cause of the problem.

@GreggFranklin Did you add the wp-config.php file or is this the un-altered version of the customer's import? Just want to know.

**Comment by davejesch** [comment] 2018-09-06 18:44
Fixed. Archive provided now imports.

**Closed as completed** 2019-05-30 03:32 UTC
Labels: bug, question, fixed
